name: My first Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: List and Read files
        run: |
          echo "My 1st Github actions workflow"
          ls
          cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      # - name: kist all files
      #   run: ls
      # - name: Read file
      #   run: cat README.md
